### ISSUE TITLE
upgrade eslint-plugin-html

### ISSUE THREAD

**Issue by mysticatea** [vuejs/eslint-plugin-vue-libs#3]
This plugin depends on `eslint-plugin-html@2`. However, it does not support ESLint 4. I want to upgrade it to latest. But it's a breaking change because the latest `eslint-plugin-html` supports only `eslint@>=4.7.0`.

Can we upgrade `eslint-plugin-html` to the latest?

**Comment by yyx990803** [comment]
Yeah, we can release a new major for this package.
