### ISSUE TITLE
Use in conjunction with eslint-plugin-vue

### ISSUE THREAD

**Issue by tbuteler** [vuejs/eslint-plugin-vue-libs#6]
I wanted to use this ruleset along with the `eslint-plugin-vue`, but cannot get them to work together. I get no output from running `eslint`.

This is what I have in the extends key of `.eslintrc.json`:

```
{
    "extends": [
        "plugin:vue/recommended",
        "plugin:vue-libs/recommended"
    ],
    ...
}
```

Switching order doesn't have any effect either, but if I copy the `vue-libs` ruleset and paste it directly in my `.eslintrc.json` rules array, then everything works as expected. Also, if I remove one or the other, it works, though I get a more limited set of rules than I intend to.

Am I doing something wrong?

**Comment by yyx990803** [comment]
They are not meant to be used together. This plugin is specifically used for only library development.
